const numbers = [16, -37, 54, -4, 72, -56, 47, 4, -16, 25, -37, 46, 4, -51, 27, -63, 4, -54, 76, -4, 12, -35, 4, 47];
const positiveNumbers = numbers.filter(number => number > 0);
const sumOfPositiveNumbers = positiveNumbers.reduce((sum, number) => sum + number, 0);
const countOfPositiveNumbers = positiveNumbers.length;
const minNumber = Math.min(...numbers);
const indexOfMinNumber = numbers.indexOf(minNumber);
const maxNumber = Math.max(...numbers);
const indexOfMaxNumber = numbers.indexOf(maxNumber);
const countOfNegativeNumbers = numbers.filter(number => number < 0).length;
const oddPositiveNumbers = positiveNumbers.filter(number => number % 2 !== 0);
const evenPositiveNumbers = positiveNumbers.filter(number => number % 2 === 0);
const countOfOddPositiveNumbers = oddPositiveNumbers.length;
const countOfEvenPositiveNumbers = evenPositiveNumbers.length;
const sumOfOddPositiveNumbers = oddPositiveNumbers.reduce((sum, number) => sum + number, 0);
const sumOfEvenPositiveNumbers = evenPositiveNumbers.reduce((sum, number) => sum + number, 0);
const productOfPositiveNumbers = positiveNumbers.reduce((product, number) => product * number, 1);
const largestNumber = Math.max(...numbers);
const modifiedArray = numbers.map(number => (number === largestNumber ? number : 0));

console.log('Сума позитивних елементів:', sumOfPositiveNumbers);
console.log('Кількість позитивних елементів:', countOfPositiveNumbers);
console.log('Мінімальний елемент:', minNumber, 'Порядковий номер:', indexOfMinNumber);
console.log('Максимальний елемент:', maxNumber, 'Порядковий номер:', indexOfMaxNumber);
console.log('Кількість негативних елементів:', countOfNegativeNumbers);
console.log('Кількість непарних позитивних елементів:', countOfOddPositiveNumbers);
console.log('Кількість парних позитивних елементів:', countOfEvenPositiveNumbers);
console.log('Сума непарних позитивних елементів:', sumOfOddPositiveNumbers);
console.log('Сума парних позитивних елементів:', sumOfEvenPositiveNumbers);
console.log('Добуток позитивних елементів:', productOfPositiveNumbers);
console.log('Масив після обнулення, крім найбільшого елемента:', modifiedArray);